// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFPNQSSZiBKU-F6egPGZWYA8OMFRtSCPw',
    appId: '1:1073998792708:web:53e3e10798f9c364d9cd51',
    messagingSenderId: '1073998792708',
    projectId: 'chat-app-777a1',
    authDomain: 'chat-app-777a1.firebaseapp.com',
    storageBucket: 'chat-app-777a1.firebasestorage.app',
    measurementId: 'G-SEP6HF0DPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmK1U_7WRONECVNK0P1TEYOLUDhp7BNlU',
    appId: '1:1073998792708:android:26f12cc28e4df490d9cd51',
    messagingSenderId: '1073998792708',
    projectId: 'chat-app-777a1',
    storageBucket: 'chat-app-777a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6_xMdE_YxAQ4F9A9-HM3W1SW5Tx__0LQ',
    appId: '1:1073998792708:ios:2215947295c58882d9cd51',
    messagingSenderId: '1073998792708',
    projectId: 'chat-app-777a1',
    storageBucket: 'chat-app-777a1.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6_xMdE_YxAQ4F9A9-HM3W1SW5Tx__0LQ',
    appId: '1:1073998792708:ios:2215947295c58882d9cd51',
    messagingSenderId: '1073998792708',
    projectId: 'chat-app-777a1',
    storageBucket: 'chat-app-777a1.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFPNQSSZiBKU-F6egPGZWYA8OMFRtSCPw',
    appId: '1:1073998792708:web:0f446185196f169ad9cd51',
    messagingSenderId: '1073998792708',
    projectId: 'chat-app-777a1',
    authDomain: 'chat-app-777a1.firebaseapp.com',
    storageBucket: 'chat-app-777a1.firebasestorage.app',
    measurementId: 'G-QERTGXZFF1',
  );
}
